version: "3"
services:
       nuxt-app:
           container_name: nuxt-app
           image: my_app
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongo
           depends_on:
               - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'